# Generated by Django 3.1.2 on 2020-10-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='username')),
            ],
            options={
                'verbose_name': 'usuario permitido',
                'verbose_name_plural': 'usuarios permitidos',
            },
        ),
    ]
