# Generated by Django 3.1.2 on 2020-11-05 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reclamos.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiket', models.CharField(default=reclamos.models.seguimiento, max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('carrera', models.CharField(max_length=150)),
                ('registro', models.BigIntegerField(blank=True, null=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=100)),
                ('consulta', models.TextField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamos.categoria', verbose_name='Asunto')),
            ],
            options={
                'verbose_name_plural': 'Reclamos',
                'ordering': ('fecha_creada',),
                'permissions': (('ver_examen', 'Ver Examen'), ('ver_cursada', 'Ver Cursada'), ('ver_ingreso', 'Ver Ingreso'), ('ver_mayores_25', 'Ver Ingreso Mayores de 25'), ('ver_equivalencia', 'Ver Equivalcencia'), ('ver_programas_planes', 'Ver Certificacion de programas y planes'), ('ver_egreso', 'Ver Egreso'), ('ver_trabajo_final', 'Ver Trabajo Final'), ('ver_alumno_vocacional', 'Ver alumno vocacional'), ('ver_cambio_plan', 'Ver cambio de plan'), ('admin', 'Administrador'), ('empleado', 'Empleado')),
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.TextField()),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamos.reclamo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
